// The mascot: one image, DiceBear "Notionists" style by Zoish (CC0), generated by scripts/avatar.sh.
// Small round uses (header, chat) wrap it in .face-wrap, which crops to the head.
export function Avatar({ size = 40, className }: { size?: number; className?: string }) {
  return <img src="/avatar/nicolas.svg" width={size} height={size} alt="" className={className} draggable={false} />
}
